pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  environment {
    CI_IMAGE = 'java-ci-tools:${env.BUILD_NUMBER}'
  }  

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
        echo "Branch: ${env.BRANCH_NAME}"
      }
    }
    stage('CI - Build tools image') {
      steps {
        script {
           docker.build(env.CI_IMAGE, "-f devops/ci.Dockerfile .")
        }
      }
    }
    stage('Test') {
      /*
        `agent` dentro de un stage permite que SOLO ese stage se ejecute en un contexto concreto.
        En este caso, usamos Docker como capa de virtualizacion: los comandos se ejecutan dentro
        de un contenedor temporal.
      */
      agent {
        docker {
          //image 'maven:3.8.6-openjdk-11-slim'
          image CI_IMAGE
        }
      }
      steps {
        sh 'mvn -version'
        sh 'mvn test'
      }
    }
    stage('Prepare') {
        steps {
            // Las imágenes slim de Java tampoco suelen traer 'make'
            sh 'apt-get update && apt-get install -y make'
        }
    }
    /*stage('CI - Lint') {
      steps {
         sh 'make lint'
      }
    }*/
    /*stage('CI - Lint') {
      steps {
        sh 'apt-get update && apt-get install -y make'
        sh 'make lint' // Aquí el Makefile ejecutará: mvn -q -DskipTests=true test
      }
    }*/
    stage('CI - Test') {
      steps {
         sh 'make test'
      }
    }
  }
}
