/* 
  Practica 2 - 
*/
 
pipeline {  
  agent any

  stages {
    stage('Info') {
      steps {
        sh 'echo "Job: $JOB_NAME"'
        sh 'echo "build: $BUILD_NUMBER"'
      }      
    }
    stage('Test') {      
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
        sh 'mvn -version'
        sh 'echo "Stage dummy. En la Practica 2 ejecutaras aqui los tests unitarios."'
      }
    }
  }
}
