pipeline {
  agent any

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    stage('CI Lint') {
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
          args '-u root:root'
        }
      }
      steps {
        sh 'mvn -v'
        // Ejecuta el target lint del Makefile
        sh 'make lint'
      }
    }

    stage('CI Test') {
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
          args '-u root:root'
        }
      }
      steps {
        sh 'mvn -v'
        // Ejecuta el target test del Makefile
        sh 'make test'
      }
    }
  }
}

